name = "cloudflare-docker-proxy"
account_id = "b8488957e88658039d2a38fb8f160514"
compatibility_date = "2023-12-01"
main = "src/index.js"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.vars]
CUSTOM_DOMAIN = "evilstarss.com"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"
CUSTOM_DOMAIN = "exmaple.com"

[env.production]
name = "cloudflare-docker-proxy"
routes = [
  { pattern = "docker.evilstarss.com", custom_domain = true },
  { pattern = "quay.evilstarss.com", custom_domain = true },
  { pattern = "gcr.evilstarss.com", custom_domain = true },
  { pattern = "k8s-gcr.evilstarss.com", custom_domain = true },
  { pattern = "k8s.evilstarss.com", custom_domain = true },
  { pattern = "ghcr.evilstarss.com", custom_domain = true },
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""
CUSTOM_DOMAIN = "evilstarss.com"

[env.staging]
name = "cloudflare-docker-proxy-staging"
# route = { pattern = "docker-staging.libcuda.so", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
